# HTTP Server
[server]
	Address     = ":8500"
	ServerRoot  = "public"
	ServerAgent = "goFrame"
	LogPath     = "./runtime/log/gf-app/server"

# Logger.
[logger]
    Path        = "./runtime/log/goFrame"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{,}}"]

# Database.
[database]
    link  = "mysql:root:@tcp(127.0.0.1:3306)/blog"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "./runtime/log/goFrame/sql"
        Level  = "all"
        Stdout = true

# Redis数据库配置
[redis]
    default = "127.0.0.1:6379,0"
    cache   = "127.0.0.1:6379,1,?idleTimeout=600"

[token]
    secret="qiuapeng921"