# HTTP Server
[server]
	Address     = ":8500"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "/tmp/log/gf-app/server"

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:work:123456@tcp(192.168.0.163:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true

# Redis数据库配置
[redis]
    default = "192.168.0.163:6379,0"
    cache   = "192.168.0.163:6379,1,?idleTimeout=600"

[compiler]
        name     = "my-app"
        version  = "1.0.0"
        arch     = "i386,amd64"
        system   = "linux,windows,darwin"
        output   = ""
        path     = "./bin"
        extra    = "-ldflags \"-s -w\""
        # 自定义编译时内置变量
        [compiler.VarMap]
            author = "qiuapeng921"
            email  = "qiuapeng921@16.com"