// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package menu

import (
	"database/sql"
	"github.com/gogf/gf/database/gdb"
)

// Entity is the golang structure for table menu.
type Entity struct {
    Id         uint   `orm:"id,primary"  json:"id"`          // 主键id              
    Name       string `orm:"name"        json:"name"`        // 菜单名              
    Url        string `orm:"url"         json:"url"`         // 地址                
    Identify   string `orm:"identify"    json:"identify"`    // 标识                
    ParentId   uint   `orm:"parent_id"   json:"parent_id"`   // 上级id              
    Icon       string `orm:"icon"        json:"icon"`        // 图标                
    Status     uint   `orm:"status"      json:"status"`      // 状态 1 正常 0 删除  
    CreateTime int    `orm:"create_time" json:"create_time"` // 创建时间            
    UpdateTime int    `orm:"update_time" json:"update_time"` // 修改时间            
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (r *Entity) OmitEmpty() *arModel {
	return Model.Data(r).OmitEmpty()
}

// Inserts does "INSERT...INTO..." statement for inserting current object into table.
func (r *Entity) Insert() (result sql.Result, err error) {
	return Model.Data(r).Insert()
}

// Replace does "REPLACE...INTO..." statement for inserting current object into table.
// If there's already another same record in the table (it checks using primary key or unique index),
// it deletes it and insert this one.
func (r *Entity) Replace() (result sql.Result, err error) {
	return Model.Data(r).Replace()
}

// Save does "INSERT...INTO..." statement for inserting/updating current object into table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Save() (result sql.Result, err error) {
	return Model.Data(r).Save()
}

// Update does "UPDATE...WHERE..." statement for updating current object from table.
// It updates the record if there's already another same record in the table
// (it checks using primary key or unique index).
func (r *Entity) Update() (result sql.Result, err error) {
	return Model.Data(r).Where(gdb.GetWhereConditionOfStruct(r)).Update()
}

// Delete does "DELETE FROM...WHERE..." statement for deleting current object from table.
func (r *Entity) Delete() (result sql.Result, err error) {
	return Model.Where(gdb.GetWhereConditionOfStruct(r)).Delete()
}